// Generated by packages/zksync/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Discovered via cast call against the L1 Bridgehub anchor
// 0x303a465B659cBB0ab36eE643eA362c509EEb5213 on eip155:1.
import { parse } from "valibot"
import { ZksyncDeploysSchema } from "../core/deploys"

export const eip155_324_deploys = parse(
  ZksyncDeploysSchema,
  {
    name: "zkSync Era",
    parentChainId: 1,
    l1: {
      bridgehub:
        "0x303a465B659cBB0ab36eE643eA362c509EEb5213",
      assetRouter:
        "0x8829AD80E425C646DAB305381ff105169FeEcE56",
      nativeTokenVault:
        "0xbeD1EB542f9a5aA6419Ff3deb921A372681111f6",
      l1Nullifier:
        "0xD7f9f54194C633F36CCD5F3da84ad4a1c38cB2cB",
      messageRoot:
        "0x5Ce9257755391D1509cD4eC1899d3F88A57BB4aD",
      ctmDeployer:
        "0x6078F6B379f103de1Aa912dc46bb8Df0c8809860",
      wethToken:
        "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      diamondProxy:
        "0x32400084C286CF3E17e7B677ea9583e60a000324",
      chainTypeManager:
        "0xc2eE6b6af7d616f6e27ce7F4A451Aedc2b0F5f5C",
      baseToken:
        "0x0000000000000000000000000000000000000001",
    },
    isTestnet: false,
  },
)
