// Generated by packages/zksync/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Discovered via cast call against the L1 Bridgehub anchor
// 0x35A54c8C757806eB6820629bc82d90E056394C92 on eip155:11155111.
import { parse } from "valibot"
import { ZksyncDeploysSchema } from "../core/deploys"

export const eip155_300_deploys = parse(
  ZksyncDeploysSchema,
  {
    name: "zkSync Era Sepolia",
    parentChainId: 11155111,
    l1: {
      bridgehub:
        "0x35A54c8C757806eB6820629bc82d90E056394C92",
      assetRouter:
        "0xF2a49545C5B1A85d2fB018cC39103661639a9B06",
      nativeTokenVault:
        "0x746DBBa1edfBe1b547c87189eFE91B77d53d9E39",
      l1Nullifier:
        "0x3E8b2fe58675126ed30d0d12dea2A9bda72D18Ae",
      messageRoot:
        "0x30B8CD9F0948aBe3E2Dab4B007C063f4D89e8f4A",
      ctmDeployer:
        "0xA3dC4031C774C1Ff661C0C65EB9AcE207E3141D6",
      wethToken:
        "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9",
      diamondProxy:
        "0x9A6DE0f62Aa270A8bCB1e2610078650D539B1Ef9",
      chainTypeManager:
        "0x4e39E90746A9ee410A8Ce173C7B96D3AfEd444a5",
      baseToken:
        "0x0000000000000000000000000000000000000001",
    },
    isTestnet: true,
  },
)
