// Vendor OP Stack L1 deployment addresses from
// ethereum-optimism/superchain-registry at a pinned SHA. Run when
// adding a new chain to the allowlist, or when an upstream
// deployment changes for a chain we already ship.
//
// Usage:  pnpm --filter @ethernauta/op pull-superchain-registry
//
// Outputs:  packages/op/src/deploys/eip155-<chainId>.ts
//
// Bump cadence: on demand. The registry doesn't follow a tagged
// release cadence; pin to a `main`-branch commit chosen at the
// time of refresh. The SHA below is mirrored in
// packages/op/src/deploys/SOURCES.md — keep them in sync.

import { execSync } from "node:child_process"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { parse, record, string } from "valibot"

const REGISTRY_SHA =
  "8b1e9dbca4dd2021a4239651ef645fbe9bc725d2"
const ADDRESSES_URL = `https://raw.githubusercontent.com/ethereum-optimism/superchain-registry/${REGISTRY_SHA}/superchain/extra/addresses/addresses.json`

// Chains we ship in v1. Each must exist as `eip155-<id>.ts` in
// @ethernauta/chain (the subset invariant — see plan D8). If
// upstream enumerates a chain we want that doesn't exist in
// @ethernauta/chain, the script throws so the missing chain is
// added there first.
const CHAIN_IDS = [
  10, // OP Mainnet
  11155420, // OP Sepolia
  480, // Worldchain
  1868, // Soneium
  34443, // Mode
  7777777, // Zora
] as const

// Field-name routing. Anything in upstream's flat addresses.json
// is bucketed into "contracts" or "roles" per the Standard
// Rollup Charter shape (validation/standard/standard-config-roles-*.toml
// + standard-versions-*.toml).
const ROLE_FIELDS = new Set([
  "BatchSubmitter",
  "Challenger",
  "Guardian",
  "Proposer",
  "ProxyAdminOwner",
  "SystemConfigOwner",
  "UnsafeBlockSigner",
])

const UpstreamSchema = record(
  string(),
  record(string(), string()),
)

async function fetch_addresses() {
  const response = await fetch(ADDRESSES_URL)
  if (!response.ok) {
    throw new Error(
      `failed to fetch ${ADDRESSES_URL}: ${response.status} ${response.statusText}`,
    )
  }
  const raw = await response.json()
  return parse(UpstreamSchema, raw)
}

function bucket_fields(entry: Record<string, string>) {
  const contracts: Record<string, string> = {}
  const roles: Record<string, string> = {}
  for (const [field, value] of Object.entries(entry)) {
    if (ROLE_FIELDS.has(field)) {
      roles[field] = value
    } else {
      contracts[field] = value
    }
  }
  return { contracts, roles }
}

function emit_field_lines(fields: Record<string, string>) {
  return Object.entries(fields)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, address]) => `    ${name}: "${address}",`)
    .join("\n")
}

function emit_file(
  chain_id: number,
  entry: Record<string, string>,
) {
  const { contracts, roles } = bucket_fields(entry)
  return `// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ ${REGISTRY_SHA.slice(0, 12)}…
//   superchain/extra/addresses/addresses.json["${chain_id}"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_${chain_id}_deploys = parse(OpDeploysSchema, {
  contracts: {
${emit_field_lines(contracts)}
  },
  roles: {
${emit_field_lines(roles)}
  },
})
`
}

async function main() {
  const upstream = await fetch_addresses()
  const here = dirname(fileURLToPath(import.meta.url))
  const deploys_root = resolve(here, "..", "src", "deploys")
  mkdirSync(deploys_root, { recursive: true })

  console.log(
    `Pulling OP Stack deployments from superchain-registry @ ${REGISTRY_SHA.slice(0, 12)}…`,
  )
  for (const chain_id of CHAIN_IDS) {
    const entry = upstream[String(chain_id)]
    if (!entry) {
      throw new Error(
        `chain ${chain_id} not present in upstream addresses.json at this SHA`,
      )
    }
    const out_path = join(
      deploys_root,
      `eip155-${chain_id}.ts`,
    )
    writeFileSync(out_path, emit_file(chain_id, entry))
    const field_count = Object.keys(entry).length
    console.log(
      `  eip155-${chain_id}.ts — ${field_count} fields`,
    )
  }
  console.log("Formatting generated files…")
  execSync(`biome format --write "${deploys_root}"`, {
    stdio: "inherit",
  })
  console.log("Done.")
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
