// Derivation script — downloads the Unicode UCD inputs we
// need to implement NFC and emits a single readable TS
// data module at `src/data/nfc.ts`.
//
// Inputs (public, hosted by unicode.org):
//   - UnicodeData.txt              (decompositions, ccc)
//   - CompositionExclusions.txt    (exclusions)
//
// Output:
//   - src/data/nfc.ts
//
// Rerun via `pnpm derive` when bumping UCD_VERSION below.

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const UCD_VERSION = "16.0.0"
const UCD_BASE = `https://www.unicode.org/Public/${UCD_VERSION}/ucd`

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_PATH = join(HERE, "..", "data", "nfc.ts")

type Row = {
  cp: number
  ccc: number
  decomp: number[] | null
}

function parse_unicode_data(_text: string): Row[] {
  const rows: Row[] = []
  for (const raw_line of _text.split("\n")) {
    const line = raw_line.trim()
    if (line.length === 0) continue
    const fields = line.split(";")
    const cp = Number.parseInt(fields[0] as string, 16)
    const ccc = Number.parseInt(fields[3] as string, 10)
    const decomp_field = (fields[5] as string).trim()
    let decomp: number[] | null = null
    if (decomp_field.length > 0) {
      // Skip compatibility decompositions (those tagged
      // like `<compat>`, `<font>`, etc.). NFC only uses
      // canonical decompositions.
      if (!decomp_field.startsWith("<")) {
        decomp = decomp_field
          .split(" ")
          .map((cp_hex) => Number.parseInt(cp_hex, 16))
      }
    }
    rows.push({ cp, ccc, decomp })
  }
  return rows
}

function parse_exclusions(_text: string): Set<number> {
  const out = new Set<number>()
  for (const raw_line of _text.split("\n")) {
    const line = raw_line.split("#")[0]?.trim() ?? ""
    if (line.length === 0) continue
    out.add(Number.parseInt(line, 16))
  }
  return out
}

function build_ccc_data(_rows: Row[]): number[] {
  const out: number[] = []
  for (const row of _rows) {
    if (row.ccc !== 0) {
      out.push(row.cp, row.ccc)
    }
  }
  return out
}

function build_decomp_data(_rows: Row[]): number[] {
  const out: number[] = []
  for (const row of _rows) {
    if (row.decomp === null) continue
    out.push(row.cp, row.decomp.length, ...row.decomp)
  }
  return out
}

function build_comp_data(
  _rows: Row[],
  _exclusions: Set<number>,
): number[] {
  const out: number[] = []
  for (const row of _rows) {
    if (row.decomp === null) continue
    // NFC composition only inverts decompositions that:
    //   1. are a length-2 sequence
    //   2. are not in the composition exclusions list
    //   3. do not start with a non-zero combining class
    //      (these are "non-starter decompositions")
    if (row.decomp.length !== 2) continue
    if (_exclusions.has(row.cp)) continue
    const [a, b] = row.decomp as [number, number]
    out.push(a, b, row.cp)
  }
  return out
}

function format_array(
  _name: string,
  _data: number[],
): string {
  const chunks: string[] = []
  const CHUNK = 12
  for (let i = 0; i < _data.length; i += CHUNK) {
    const slice = _data.slice(i, i + CHUNK)
    chunks.push(
      `  ${slice.map((n) => `0x${n.toString(16)}`).join(", ")},`,
    )
  }
  return `export const ${_name}: readonly number[] = [\n${chunks.join("\n")}\n]`
}

async function fetch_text(_url: string): Promise<string> {
  console.log(`fetching ${_url}`)
  const response = await fetch(_url)
  if (!response.ok) {
    throw new Error(
      `failed to fetch ${_url}: ${response.status}`,
    )
  }
  return await response.text()
}

async function main(): Promise<void> {
  const [unicode_data_text, exclusions_text] =
    await Promise.all([
      fetch_text(`${UCD_BASE}/UnicodeData.txt`),
      fetch_text(`${UCD_BASE}/CompositionExclusions.txt`),
    ])

  const rows = parse_unicode_data(unicode_data_text)
  const exclusions = parse_exclusions(exclusions_text)

  const ccc_data = build_ccc_data(rows)
  const decomp_data = build_decomp_data(rows)
  const comp_data = build_comp_data(rows, exclusions)

  const header = [
    "// Auto-generated by src/derive/nfc.ts. DO NOT EDIT.",
    `// Source: Unicode UCD ${UCD_VERSION}`,
    "//   https://www.unicode.org/Public/" +
      UCD_VERSION +
      "/ucd/UnicodeData.txt",
    "//   https://www.unicode.org/Public/" +
      UCD_VERSION +
      "/ucd/CompositionExclusions.txt",
    "//",
    "// Layout:",
    "//   CCC_DATA    — flat pairs of (codepoint, ccc)",
    "//   DECOMP_DATA — packed (cp, len, ...sequence)",
    "//   COMP_DATA   — flat triples of (a, b, composed)",
    "// All values are decoded by src/nfc.ts at module load.",
  ].join("\n")

  const body = [
    header,
    "",
    `export const UCD_VERSION = "${UCD_VERSION}" as const`,
    "",
    format_array("CCC_DATA", ccc_data),
    "",
    format_array("DECOMP_DATA", decomp_data),
    "",
    format_array("COMP_DATA", comp_data),
    "",
  ].join("\n")

  mkdirSync(dirname(OUT_PATH), { recursive: true })
  writeFileSync(OUT_PATH, body)

  const decomp_count = rows.filter(
    (r) => r.decomp !== null,
  ).length

  console.log(`wrote ${OUT_PATH}`)
  console.log(`  CCC entries:    ${ccc_data.length / 2}`)
  console.log(`  DECOMP entries: ${decomp_count}`)
  console.log(`  COMP entries:   ${comp_data.length / 3}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
