// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["60808"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_60808_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0xF2dc77c697e892542cC53336178a78Bb313DFDC7",
    AnchorStateRegistryProxy:
      "0xC9AC21AcD8696B64270716528bF83630Ea7a293c",
    DelayedWETHProxy:
      "0x1A08BA77CB95184Ea0C31e56f199Db068eb6B35d",
    DisputeGameFactoryProxy:
      "0x96123dbFC3253185B594c6a7472EE5A21E9B1079",
    L1CrossDomainMessengerProxy:
      "0xE3d981643b806FB8030CDB677D6E60892E547EdA",
    L1ERC721BridgeProxy:
      "0x5fF93263D5181b2A826f8c51d54BC0da2d20D50a",
    L1StandardBridgeProxy:
      "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0x5557408ab14013ce9Dbb300dE0D87D386BB09cb6",
    OptimismPortalProxy:
      "0x8AdeE124447435fE03e3CD24dF3f4cAE32E65a3E",
    PermissionedDisputeGame:
      "0x15F80920C8Fec136e2A804E04f26203FF8dAd19A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0x0d9f416260598313Be6FDf6B010f2FbC34957Cd0",
    SuperchainConfig:
      "0xE925205ad05D8d612Ac205C4941CCd61Fc965C46",
    SystemConfigProxy:
      "0xACB886b75D76d1c8d9248cFdDfA09b70C71c5393",
  },
  roles: {
    BatchSubmitter:
      "0x08F9F14fF43E112B18c96f0986F28Cb1878f1D11",
    Challenger:
      "0xC91482A96e9c2A104d9298D1980eCCf8C4dc764E",
    Guardian: "0xC91482A96e9c2A104d9298D1980eCCf8C4dc764E",
    Proposer: "0x7cB1022D30b9860C36b243E7B181A1d46f618C69",
    ProxyAdminOwner:
      "0xC91482A96e9c2A104d9298D1980eCCf8C4dc764E",
    SystemConfigOwner:
      "0xC91482A96e9c2A104d9298D1980eCCf8C4dc764E",
    UnsafeBlockSigner:
      "0xB18AD28cB78fD2eAfAc6941c24c5135515B796f0",
  },
})
