// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["130"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_130_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x8098F676033A377b9Defe302e9fE6877cD63D575",
    AnchorStateRegistryProxy:
      "0x27Cf508E4E3Aa8d30b3226aC3b5Ea0e8bcaCAFF9",
    DelayedWETHProxy:
      "0x0bdbEc6bd35571F97f96f3ed21822a4f2e071A3c",
    DisputeGameFactoryProxy:
      "0x2F12d621a16e2d3285929C9996f478508951dFe4",
    EthLockboxProxy:
      "0x08bA0023eD60C7Bd040716dD13C45fA0062df5C5",
    FaultDisputeGame:
      "0x6dDBa09bc4cCB0D6Ca9Fc5350580f74165707499",
    L1CrossDomainMessengerProxy:
      "0x9A3D64E386C18Cb1d6d5179a9596A4B5736e98A6",
    L1ERC721BridgeProxy:
      "0xD04D0D87E0bd4D2E50286760a3EF323FeA6849Cf",
    L1StandardBridgeProxy:
      "0x81014F44b0a345033bB2b3B21C7a1A308B35fEeA",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0xA2B597EaeAcb6F627e088cbEaD319e934ED5edad",
    OptimismPortalProxy:
      "0x0bd48f6B86a26D3a217d0Fa6FfE2B491B956A7a2",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0x3B73Fa8d82f511A3caE17B5a26E4E1a2d5E2f2A4",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0xc407398d063f942feBbcC6F80a156b47F3f1BDA6",
  },
  roles: {
    BatchSubmitter:
      "0x2F60A5184c63ca94f82a27100643DbAbe4F3f7Fd",
    Challenger:
      "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0xD5F0E2912C70771C589CD8bB087EDE0Dab4AFA9A",
    ProxyAdminOwner:
      "0x6d5B183F538ABB8572F5cD17109c617b994D5833",
    SystemConfigOwner:
      "0x9245d5D10AA8a842B31530De71EA86c0760Ca1b1",
    UnsafeBlockSigner:
      "0x833C6f278474A78658af91aE8edC926FE33a230e",
  },
})
