// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["57073"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_57073_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x9b7C9BbD6d540A8A4dEDd935819fC4408Ba71153",
    AnchorStateRegistryProxy:
      "0xEe018bAf058227872540AC60eFbd38b023d9dAe2",
    DelayedWETHProxy:
      "0x6Cbd14DA021e39A7895Ae151Ac72eCc9023e87F6",
    DisputeGameFactoryProxy:
      "0x10d7B35078d3baabB96Dd45a9143B94be65b12CD",
    EthLockboxProxy:
      "0xbd4AbB321138e8Eddc399cE64E66451294325a14",
    FaultDisputeGame:
      "0x6dDBa09bc4cCB0D6Ca9Fc5350580f74165707499",
    L1CrossDomainMessengerProxy:
      "0x69d3Cf86B2Bf1a9e99875B7e2D9B6a84426c171f",
    L1ERC721BridgeProxy:
      "0x661235a238B11191211fa95D4Dd9E423d521E0Be",
    L1StandardBridgeProxy:
      "0x88FF1e5b602916615391F55854588EFcBB7663f0",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0xA8B389A82e088b164cD03230e900980CcED34d29",
    OptimismPortalProxy:
      "0x5d66C1782664115999C47c9fA5cd031f495D3e4F",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0xd56045E68956FCe2576E680c95a4750cf8241f79",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x62C0a111929fA32ceC2F76aDba54C16aFb6E8364",
  },
  roles: {
    BatchSubmitter:
      "0x500d7Ea63CF2E501dadaA5feeC1FC19FE2Aa72Ac",
    Challenger:
      "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x65436ddCbc026F34118954F229f7F132b696b3B4",
    ProxyAdminOwner:
      "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A",
    SystemConfigOwner:
      "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb",
    UnsafeBlockSigner:
      "0x7D056B99AA2021864c42E25B4F8cE3BdEAc9463C",
  },
})
