// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["11155420"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_11155420_deploys = parse(
  OpDeploysSchema,
  {
    contracts: {
      AddressManager:
        "0x9bFE9c5609311DF1c011c47642253B78a4f33F4B",
      AnchorStateRegistryProxy:
        "0xa1Cec548926eb5d69aa3B7B57d371EdBdD03e64b",
      DelayedWETHProxy:
        "0x1Bf7Ea64F9339CE5468c2947151c18E2a1229B76",
      DisputeGameFactoryProxy:
        "0x05F9613aDB30026FFd634f38e5C4dFd30a197Fa1",
      EthLockboxProxy:
        "0xC38de74A8B0F6C671669cfB36e160548Fb4A0c05",
      FaultDisputeGame:
        "0x6dDBa09bc4cCB0D6Ca9Fc5350580f74165707499",
      L1CrossDomainMessengerProxy:
        "0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef",
      L1ERC721BridgeProxy:
        "0xd83e03D576d23C9AEab8cC44Fa98d058D2176D1f",
      L1StandardBridgeProxy:
        "0xFBb0621E0B23b5478B630BD55a5f21f67730B0F1",
      MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
      OptimismMintableERC20FactoryProxy:
        "0x868D59fF9710159C2B330Cc0fBDF57144dD7A13b",
      OptimismPortalProxy:
        "0x16Fc5058F25648194471939df75CF27A2fdC48BC",
      PermissionedDisputeGame:
        "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
      PreimageOracle:
        "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
      ProxyAdmin:
        "0x189aBAAaa82DfC015A588A7dbaD6F13b1D3485Bc",
      SuperchainConfig:
        "0xC2Be75506d5724086DEB7245bd260Cc9753911Be",
      SystemConfigProxy:
        "0x034edD2A225f7f429A63E0f1D2084B9E0A93b538",
    },
    roles: {
      BatchSubmitter:
        "0x8F23BB38F531600e5d8FDDaAEC41F13FaB46E98c",
      Challenger:
        "0xfd1D2e729aE8eEe2E146c033bf4400fE75284301",
      Guardian:
        "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E",
      Proposer:
        "0x49277EE36A024120Ee218127354c4a3591dc90A9",
      ProxyAdminOwner:
        "0x1Eb2fFc903729a0F03966B917003800b145F56E2",
      SystemConfigOwner:
        "0xfd1D2e729aE8eEe2E146c033bf4400fE75284301",
      UnsafeBlockSigner:
        "0x57CACBB0d30b01eb2462e5dC940c161aff3230D3",
    },
  },
)
