// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["10"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_10_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0xdE1FCfB0851916CA5101820A69b13a4E276bd81F",
    AnchorStateRegistryProxy:
      "0x23B2C62946350F4246f9f9D027e071f0264FD113",
    DelayedWETHProxy:
      "0xD061AB95069987868768818cc1248705351e2D0e",
    DisputeGameFactoryProxy:
      "0xe5965Ab5962eDc7477C8520243A95517CD252fA9",
    EthLockboxProxy:
      "0x322b47Ff1FA8D5611F761e3E275C45B71b294D43",
    FaultDisputeGame:
      "0x6dDBa09bc4cCB0D6Ca9Fc5350580f74165707499",
    L1CrossDomainMessengerProxy:
      "0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1",
    L1ERC721BridgeProxy:
      "0x5a7749f83b81B301cAb5f48EB8516B986DAef23D",
    L1StandardBridgeProxy:
      "0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0x75505a97BD334E7BD3C476893285569C4136Fa0F",
    OptimismPortalProxy:
      "0xbEb5Fc579115071764c7423A4f12eDde41f106Ed",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0x543bA4AADBAb8f9025686Bd03993043599c6fB04",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x229047fed2591dbec1eF1118d64F7aF3dB9EB290",
  },
  roles: {
    BatchSubmitter:
      "0x6887246668a3b87F54DeB3b94Ba47a6f63F32985",
    Challenger:
      "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x473300df21D047806A082244b417f96b32f13A33",
    ProxyAdminOwner:
      "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A",
    SystemConfigOwner:
      "0x847B5c174615B1B7fDF770882256e2D3E95b9D92",
    UnsafeBlockSigner:
      "0xAAAA45d9549EDA09E70937013520214382Ffc4A2",
  },
})
