// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["480"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_480_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x5891090d5085679714cb0e62f74950a3c19146a8",
    AnchorStateRegistryProxy:
      "0x90BB48fe3310499Db36437dCAE642F721e32d094",
    DelayedWETHProxy:
      "0xb705030703Bf8ff4300bd6FBD8dE63CE8492f575",
    DisputeGameFactoryProxy:
      "0x069c4c579671f8c120b1327a73217D01Ea2EC5ea",
    L1CrossDomainMessengerProxy:
      "0xf931a81D18B1766d15695ffc7c1920a62b7e710a",
    L1ERC721BridgeProxy:
      "0x1Df436AfDb2fBB40F1fE8bEd4Fc89A0D0990a8E9",
    L1StandardBridgeProxy:
      "0x470458C91978D2d929704489Ad730DC3E3001113",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0x82Cb528466cF22412d89bdBE9bCF04856790dD0e",
    OptimismPortalProxy:
      "0xd5ec14a83B7d95BE1E2Ac12523e2dEE12Cbeea6C",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0xd7405BE7f3e63b094Af6C7C23D5eE33Fd82F872D",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x6ab0777fD0e609CE58F939a7F70Fe41F5Aa6300A",
  },
  roles: {
    BatchSubmitter:
      "0xdBBE3D8c2d2b22A2611c5A94A9a12C2fCD49Eb29",
    Challenger:
      "0xA4fB12D15Eb85dc9284a7df0AdBC8B696EdbbF1d",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x2307278fC8aB0005974A6DeD2FA6d1187333a223",
    ProxyAdminOwner:
      "0xA4fB12D15Eb85dc9284a7df0AdBC8B696EdbbF1d",
    SystemConfigOwner:
      "0xB2aa0C2C4fD6BFCBF699d4c787CD6Cc0dC461a9d",
    UnsafeBlockSigner:
      "0x2270d6eC8E760daA317DD978cFB98C8f144B1f3A",
  },
})
