// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["7777777"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_7777777_deploys = parse(
  OpDeploysSchema,
  {
    contracts: {
      AddressManager:
        "0xEF8115F2733fb2033a7c756402Fc1deaa56550Ef",
      AnchorStateRegistryProxy:
        "0x54027b388330415a34b2dBa9E6d25895649eEFf1",
      DelayedWETHProxy:
        "0x842ffD6EB189bccDbb817E1cee3286434eD7Ae6E",
      DisputeGameFactoryProxy:
        "0xB0F15106fa1e473Ddb39790f197275BC979Aa37e",
      L1CrossDomainMessengerProxy:
        "0xdC40a14d9abd6F410226f1E6de71aE03441ca506",
      L1ERC721BridgeProxy:
        "0x83A4521A3573Ca87f3a971B169C5A0E1d34481c3",
      L1StandardBridgeProxy:
        "0x3e2Ea9B92B7E48A52296fD261dc26fd995284631",
      MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
      OptimismMintableERC20FactoryProxy:
        "0xc52BC7344e24e39dF1bf026fe05C4e6E23CfBcFf",
      OptimismPortalProxy:
        "0x1a0ad011913A150f69f6A19DF447A0CfD9551054",
      PermissionedDisputeGame:
        "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
      PreimageOracle:
        "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
      ProxyAdmin:
        "0xD4ef175B9e72cAEe9f1fe7660a6Ec19009903b49",
      SuperchainConfig:
        "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
      SystemConfigProxy:
        "0xA3cAB0126d5F504B071b81a3e8A2BBBF17930d86",
    },
    roles: {
      BatchSubmitter:
        "0x625726c858dBF78c0125436C943Bf4b4bE9d9033",
      Challenger:
        "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
      Guardian:
        "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
      Proposer:
        "0x48247032092e7b0ecf5dEF611ad89eaf3fC888Dd",
      ProxyAdminOwner:
        "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A",
      SystemConfigOwner:
        "0xC72aE5c7cc9a332699305E29F68Be66c73b60542",
      UnsafeBlockSigner:
        "0x3Dc8Dfd0709C835cAd15a6A27e089FF4cF4C9228",
    },
  },
)
