// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["34443"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_34443_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x50eF494573f28Cad6B64C31b7a00Cdaa48306e15",
    AnchorStateRegistryProxy:
      "0xEB9d917868276cee5457609dbBF470FdE41BADE8",
    DelayedWETHProxy:
      "0x1C823D585B2b4325A0DB845cEBe32FC7Ad67514a",
    DisputeGameFactoryProxy:
      "0x6f13EFadABD9269D6cEAd22b448d434A1f1B433E",
    L1CrossDomainMessengerProxy:
      "0x95bDCA6c8EdEB69C98Bd5bd17660BaCef1298A6f",
    L1ERC721BridgeProxy:
      "0x2901dA832a4D0297FF0691100A8E496626cc626D",
    L1StandardBridgeProxy:
      "0x735aDBbE72226BD52e818E7181953f42E3b0FF21",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0x69216395A62dFb243C05EF4F1C27AF8655096a95",
    OptimismPortalProxy:
      "0x8B34b14c7c7123459Cf3076b8Cb929BE097d0C07",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0x470d87b1dae09a454A43D1fD772A561a03276aB7",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x5e6432F18Bc5d497B1Ab2288a025Fbf9D69E2221",
  },
  roles: {
    BatchSubmitter:
      "0x99199a22125034c808ff20f377d91187E8050F2E",
    Challenger:
      "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x674F64D64Ddc198db83cd9047dF54BF89cCD0ddB",
    ProxyAdminOwner:
      "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A",
    SystemConfigOwner:
      "0x4a4962275DF8C60a80d3a25faEc5AA7De116A746",
    UnsafeBlockSigner:
      "0xa7fA9CA4ac88686A542C0f830d7378eAB4A0278F",
  },
})
