// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["1868"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_1868_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0xB24bFEeCE1B3b7A44559F4Cbc21BeD312b130b70",
    AnchorStateRegistryProxy:
      "0x4890928941e62e273dA359374b105F803329F473",
    DelayedWETHProxy:
      "0x70277624cdE90492231Eb23309e1251Beb18Dff5",
    DisputeGameFactoryProxy:
      "0x512A3d2c7a43BD9261d2B8E8C9c70D4bd4D503C0",
    EthLockboxProxy:
      "0x67B4de6FfA66EF201Ea6099A89cA397D56622E31",
    L1CrossDomainMessengerProxy:
      "0x9CF951E3F74B644e621b36Ca9cea147a78D4c39f",
    L1ERC721BridgeProxy:
      "0x5933e323bE8896DfaCd1cD671442F27dAA10a053",
    L1StandardBridgeProxy:
      "0xeb9bf100225c214Efc3E7C651ebbaDcF85177607",
    MIPS: "0x6463dEE3828677F6270d83d45408044fc5eDB908",
    OptimismMintableERC20FactoryProxy:
      "0xc1047e30EFC9E172cFe7aa0219895B6a43fC415F",
    OptimismPortalProxy:
      "0x88e529A6ccd302c948689Cd5156C83D4614FAE92",
    PermissionedDisputeGame:
      "0x58bf355C5d4EdFc723eF89d99582ECCfd143266A",
    PreimageOracle:
      "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3",
    ProxyAdmin:
      "0x89889B569c3a505f3640ee1Bd0ac1D557f436D2a",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x7A8Ed66B319911A0F3E7288BDdAB30d9c0C875c3",
  },
  roles: {
    BatchSubmitter:
      "0x6776BE80dBAda6A02B5F2095cF13734ac303B8d1",
    Challenger:
      "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x400c164C4a8cA84385B70EEd6eB03ea847c8E1b8",
    ProxyAdminOwner:
      "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A",
    SystemConfigOwner:
      "0x509182eC226b3B71D36A3255A80EF0b1A9D43033",
    UnsafeBlockSigner:
      "0x7c2Bd59ee2a2C7391c9A240132f26071e9546262",
  },
})
