// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["7560"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_7560_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x19b5804B88F10262A55ac731f28A3BbC4209853a",
    AnchorStateRegistryProxy:
      "0x0Ca6c5aef8dBC91368C61871fDC51Ef884843e07",
    DelayedWETHProxy:
      "0x6A9AFfDcfeF73f66177a1386590607F444520571",
    DisputeGameFactoryProxy:
      "0xaCc66304d26a01A9bd60d0584dCEdbaCeC8e10e0",
    L1CrossDomainMessengerProxy:
      "0x3c01ebF22e9c111528c1E027D68944eDaB08Dfc9",
    L1ERC721BridgeProxy:
      "0x4F4B716627D2Ba0439327Ce8B563b4443aF47Dbd",
    L1StandardBridgeProxy:
      "0x12a580c05466eefb2c467C6b115844cDaF55B255",
    MIPS: "0x5fE03a12C1236F9C22Cb6479778DDAa4bce6299C",
    OptimismMintableERC20FactoryProxy:
      "0x51A00470Eb50D758EcFF3B96DB0bF4A8e86268F4",
    OptimismPortalProxy:
      "0x1d59bc9fcE6B8E2B1bf86D4777289FFd83D24C99",
    PermissionedDisputeGame:
      "0x719206d1C83D16FBcAB21f9e9DBF5A8178567E2b",
    PreimageOracle:
      "0x9c065e11870B891D214Bc2Da7EF1f9DDFA1BE277",
    ProxyAdmin:
      "0x7E54107731EC43e78DA678DFa5fB6222Ad036e03",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x5D1F4bbaF6D484fA9D5D9705f92dE6063bff6055",
  },
  roles: {
    BatchSubmitter:
      "0x6AdE72DA6C1d47c856f13CD01Aac22A90D722e01",
    Challenger:
      "0xE363e5aeAbf7F6c20589a774fCD83389ebBF0275",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x0DE6711cE623d03f0888310ca3A04a69DE0E12e1",
    ProxyAdminOwner:
      "0xc2259E7Fb719411f97aBdCdf449f6Ba3B9D75398",
    SystemConfigOwner:
      "0x68ca4cDCb0F47457273B554E60ff8321D5C133E4",
    UnsafeBlockSigner:
      "0x1F316F0F898AAb1919F9Fb9183F8D1900F721AdB",
  },
})
