// Generated by packages/op/scripts/pull-superchain-registry.ts.
// Do not edit by hand — re-run the script to bump.
// Source: superchain-registry @ 8b1e9dbca4dd…
//   superchain/extra/addresses/addresses.json["1135"]
import { parse } from "valibot"
import { OpDeploysSchema } from "../core/deploys"

export const eip155_1135_deploys = parse(OpDeploysSchema, {
  contracts: {
    AddressManager:
      "0x2dF7057d3F25212E51aFEA8dA628668229Ea423f",
    AnchorStateRegistryProxy:
      "0x7ad0d165B9607960AD850090DDd7B9eB381D9c1e",
    DelayedWETHProxy:
      "0x31eFC2c8012c56E007E5Bdb8E5B7955D197C168e",
    DisputeGameFactoryProxy:
      "0x0CF7D3706a27CCE2017aEB11E8a9c8b5388c282C",
    L1CrossDomainMessengerProxy:
      "0x31B72D76FB666844C41EdF08dF0254875Dbb7edB",
    L1ERC721BridgeProxy:
      "0x3A44A3b263FB631cdbf25f339e2D29497511A81f",
    L1StandardBridgeProxy:
      "0x2658723Bf70c7667De6B25F99fcce13A16D25d08",
    MIPS: "0x5fE03a12C1236F9C22Cb6479778DDAa4bce6299C",
    OptimismMintableERC20FactoryProxy:
      "0xc1dA06CC5DD5cE23bABa924463de7F762039252d",
    OptimismPortalProxy:
      "0x26dB93F8b8b4f7016240af62F7730979d353f9A7",
    PermissionedDisputeGame:
      "0x095102Ec7bea1c5f25090705b196a6EA2e6b64f6",
    PreimageOracle:
      "0x9c065e11870B891D214Bc2Da7EF1f9DDFA1BE277",
    ProxyAdmin:
      "0xeC432c4F1d0E12737f3a42a459B84848Af979b2d",
    SuperchainConfig:
      "0x95703e0982140D16f8ebA6d158FccEde42f04a4C",
    SystemConfigProxy:
      "0x05f23282FFDCA8286E4738C1aF79079f3d843750",
  },
  roles: {
    BatchSubmitter:
      "0xa6Ea2f3299b63c53143c993d2d5E60A69Cd6Fe24",
    Challenger:
      "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb",
    Guardian: "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2",
    Proposer: "0x0AbD6da1cE10D1cD6c7C9C14b905786D20f3EB23",
    ProxyAdminOwner:
      "0xECd4150ABbb1EBff13f74e42Fb43C3d78B4E0b45",
    SystemConfigOwner:
      "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb",
    UnsafeBlockSigner:
      "0xb9DE90a90c5E441C483e754FE7341100D5fbaEcA",
  },
})
