// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_660279_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Xai",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x7dd8A76bdAeBE3BBBaCD7Aa87f1D4FDa1E60f94f",
      sequencerInbox:
        "0x995a9d3ca121D48d21087eDE20bc8acb2398c8B1",
      outbox: "0x1E400568AD4840dbE50FB32f306B842e9ddeF726",
      rollup: "0xC47DacFbAa80Bd9D8112F4e8069482c2A3221336",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
