// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_70700_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Proof of Play Apex",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x074fFD20C6D8865752C997f4980Cf70F2a3Fbac6",
      sequencerInbox:
        "0xa58F38102579dAE7C584850780dDA55744f67DF1",
      outbox: "0x0cD85675897B7020d7121e63AB250d3F47ff3Ff2",
      rollup: "0x65AD139061B3f6DDb16170a07b925337ddf42407",
    },
    confirmPeriodBlocks: 40320,
    isBold: true,
    isTestnet: false,
  },
)
