// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_2911_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "HYCHAIN",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x73C6af7029E714DFf1F1554F88b79B335011Da68",
      sequencerInbox:
        "0xaF5800ADF22301968613c37DA9C3C2a486eA915A",
      outbox: "0x0389E24A4Bc96518169f83F50FCDdA442dD8eAFd",
      rollup: "0x8f98f9ae2f2836Ed3a628c23311Ad9976B9fBF1B",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
