// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_1996_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Sanko",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x2f285781B8d58678a3483de52D618198E4d27532",
      sequencerInbox:
        "0x24B68936C13A414cd91437aE7AA730321B9ff159",
      outbox: "0x575d32f7ff0C72921645e302cb14d2757E300786",
      rollup: "0x9A59EdF7080fdA05396373a85DdBf2cEBDB81Cd4",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
