// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_1729_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Reya Network",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x383c03c4EfF819E73409DbC690755a9992393814",
      sequencerInbox:
        "0x6CA2A628fb690Bd431F4aA608655ce37c66aff9d",
      outbox: "0x3f373b0A7DcEe7b7bCfC16DF85CfAE18388542c9",
      rollup: "0x448Bbd134dE1B23976073aB4F2915849b2dcD73A",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
