// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_21000000_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Corn",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x7E31f112d340a4D0cB0e4bD82f2853089d1bF10C",
      sequencerInbox:
        "0x4ad144ea249A98F77e0b78104D3B6eB6cd3a76DA",
      outbox: "0x2a3C554f212E3e0c78eaF0808f5313A10542dA2d",
      rollup: "0x09eD7e66Dd7c7129Ec3994498A521B502Ca7D61b",
    },
    confirmPeriodBlocks: 40320,
    isBold: true,
    isTestnet: false,
  },
)
