// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_10241024_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "AlienX",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x69aB55146Bc52A0b31F74dBDc527b8B7e9c7C27c",
      sequencerInbox:
        "0xb7d188eb30e7984f93Bec34Ee8b45A148bd594C6",
      outbox: "0xCA2AA2AA53C2225849Cc711FD472E4D2bFcD634b",
      rollup: "0x6fa8b24c85409A4fcb541c9964766862aA007f39",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
