// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_98865_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Plume",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x35381f63091926750F43b2A7401B083263aDEF83",
      sequencerInbox:
        "0x85eC1b9138a8b9659A51e2b51bb0861901040b59",
      outbox: "0x7e4627bC114Fcd12ba912103279FD2858E644E71",
      rollup: "0x4eD3F488a5a4417839BbC39712EB76D8Aaee6eE8",
    },
    confirmPeriodBlocks: 40320,
    isBold: true,
    isTestnet: false,
  },
)
