// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_7887_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Kinto",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x859a53Fe2C8DA961387030E7CB498D6D20d0B2DB",
      sequencerInbox:
        "0xF4Ef823D57819AC7202a081A5B49376BD28E7b3a",
      outbox: "0x655761AD5FC251F414D6993A73184B0669F278c8",
      rollup: "0x5073dA9cA4810f3E0aA01c20c7d9d02C3f522e11",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
