// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_1380012617_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "RARI Chain",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x255f80Ef2F09FCE0944faBb292b8510F01316Cf0",
      sequencerInbox:
        "0xA436f1867adD490BF1530c636f2FB090758bB6B3",
      outbox: "0x91591BB66075BCfF94AA128B003134165C3Ab83a",
      rollup: "0x2e988Ea0873C9d712628F0bf38DAFdE754927C89",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
