// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_42170_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Arbitrum Nova",
    parentChainId: 1,
    ethBridge: {
      bridge: "0xC1Ebd02f738644983b6C4B2d440b8e77DdE276Bd",
      sequencerInbox:
        "0x211E1c4c7f1bF5351Ac850Ed10FD68CFfCF6c21b",
      outbox: "0xD4B80C3D7240325D18E645B49e6535A3Bf95cc58",
      rollup: "0xE7E8cCC7c381809BDC4b213CE44016300707B7Bd",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
