// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_111188_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "re.al",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x39D2EEcC8B55f46aE64789E2494dE777cDDeED03",
      sequencerInbox:
        "0x51C4a227D59E49E26Ea07D8e4E9Af163da4c87A0",
      outbox: "0x8592Ca44dE1D354A20F75160F5602E5933D33761",
      rollup: "0xc4F7B37bE2bBbcF07373F28c61b1A259dfe49d2a",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
