// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_42161_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Arbitrum One",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x8315177aB297bA92A06054cE80a67Ed4DBd7ed3a",
      sequencerInbox:
        "0x1c479675ad559DC151F6Ec7ed3FbF8ceE79582B6",
      outbox: "0x0B9857ae2D4A3DBe74ffE1d7DF045bb7F96E4840",
      rollup: "0x4DCeB440657f21083db8aDd07665f8ddBe1DCfc0",
      classicOutboxes: {
        "0x667e23ABd27E623c11d4CC00ca3EC4d0bD63337a": 0,
        "0x760723CD2e632826c38Fef8CD438A4CC7E7E1A40": 30,
      },
    },
    contracts: {
      inbox: "0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f",
      l1GatewayRouter:
        "0x72Ce9c846789fdB6fC1f34aC4AD25Dd9ef7031ef",
      l1Erc20Gateway:
        "0xa3A7B6F88361F48403514059F1F16C8E78d60EeC",
      l2GatewayRouter:
        "0x5288c571Fd7aD117beA99bF60FE0846C4E84F933",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
