// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_33139_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "ApeChain",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x6B71AFb4b7725227ab944c96FE018AB9dc0434b8",
      sequencerInbox:
        "0xE6a92Ae29E24C343eE66A2B3D3ECB783d65E4a3C",
      outbox: "0x4F405BA65291063d8A524c2bDf55d4e67405c2aF",
      rollup: "0x374de579AE15aD59eD0519aeAf1A23F348Df259c",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
