// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_421614_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Arbitrum Rollup Sepolia Testnet",
    parentChainId: 11155111,
    ethBridge: {
      bridge: "0x38f918D0E9F1b721EDaA41302E399fa1B79333a9",
      sequencerInbox:
        "0x6c97864CE4bEf387dE0b3310A44230f7E3F1be0D",
      outbox: "0x65f07C7D521164a4d5DaC6eB8Fac8DA067A3B78F",
      rollup: "0xd80810638dbDF9081b72C1B33c65375e807281C8",
    },
    confirmPeriodBlocks: 20,
    isTestnet: true,
  },
)
