// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_2187_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Game7",
    parentChainId: 42161,
    ethBridge: {
      bridge: "0x20aD3d835e152F25Bf8c7B6fbC31adD32393559e",
      sequencerInbox:
        "0x4cFe930c5B2F03Cf81B44D2e62297beb79222B68",
      outbox: "0xfbe537816d181888fAbE52338a5D921eE131E9Db",
      rollup: "0x60DAdF13101C66F14C958E9141498b0C0eaE0773",
    },
    confirmPeriodBlocks: 40320,
    isBold: true,
    isTestnet: false,
  },
)
