// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_666666666_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Degen Chain",
    parentChainId: 8453,
    ethBridge: {
      bridge: "0xEfEf4558802bF373Ce3307189C79a9cAb0a4Cb9C",
      sequencerInbox:
        "0x6216dD1EE27C5aCEC7427052d3eCDc98E2bc2221",
      outbox: "0xe63ddb12FBb6211a73F12a4367b10dA0834B82da",
      rollup: "0xD34F3a11F10DB069173b32d84F02eDA578709143",
    },
    confirmPeriodBlocks: 241920,
    isBold: true,
    isTestnet: false,
  },
)
