// Generated by packages/arbitrum/scripts/pull-deploys.ts.
// Do not edit by hand — re-run the script to bump.
// Source: see packages/arbitrum/src/deploys/SOURCES.md
import { parse } from "valibot"
import { ArbitrumDeploysSchema } from "../core/deploys"

export const eip155_41455_deploys = parse(
  ArbitrumDeploysSchema,
  {
    name: "Aleph Zero EVM",
    parentChainId: 1,
    ethBridge: {
      bridge: "0x41Ec9456AB918f2aBA81F38c03Eb0B93b78E84d9",
      sequencerInbox:
        "0xF75206c49c1694594E3e69252E519434f1579876",
      outbox: "0x73bb50c32a3BD6A1032aa5cFeA048fBDA3D6aF6e",
      rollup: "0x1CA12290D954CFe022323b6A6Df92113ed6b1C98",
    },
    confirmPeriodBlocks: 45818,
    isBold: true,
    isTestnet: false,
  },
)
