// AUTO-GENERATED — do not edit. Run `pnpm --filter @ethernauta/erc generate`.

export const REGISTRY = {
  "0x00fdd58e": {
    name: "balanceOf",
    signature: "balanceOf(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["account", "id"],
  },
  "0x0178b8bf": {
    name: "resolver",
    signature: "resolver(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
  "0x01e1d114": {
    name: "totalAssets",
    signature: "totalAssets()",
    types: [],
    param_names: [],
  },
  "0x01ffc9a7": {
    name: "supportsInterface",
    signature: "supportsInterface(bytes4)",
    types: ["bytes4"],
    param_names: ["interfaceId"],
  },
  "0x02571be3": {
    name: "owner",
    signature: "owner(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
  "0x06ab5923": {
    name: "setSubnodeOwner",
    signature: "setSubnodeOwner(bytes32,bytes32,address)",
    types: ["bytes32", "bytes32", "address"],
    param_names: ["node", "label", "owner"],
  },
  "0x06fdde03": {
    name: "name",
    signature: "name()",
    types: [],
    param_names: [],
  },
  "0x07a2d13a": {
    name: "convertToAssets",
    signature: "convertToAssets(uint256)",
    types: ["uint256"],
    param_names: ["shares"],
  },
  "0x081812fc": {
    name: "getApproved",
    signature: "getApproved(uint256)",
    types: ["uint256"],
    param_names: ["tokenId"],
  },
  "0x0826ec7e": {
    name: "resolveFor",
    signature: "resolveFor(tuple,bytes)",
    types: ["tuple", "bytes"],
    param_names: ["order", "originFillerData"],
  },
  "0x095ea7b3": {
    name: "approve",
    signature: "approve(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["spender", "value"],
  },
  "0x0a28a477": {
    name: "previewWithdraw",
    signature: "previewWithdraw(uint256)",
    types: ["uint256"],
    param_names: ["assets"],
  },
  "0x0e89341c": {
    name: "uri",
    signature: "uri(uint256)",
    types: ["uint256"],
    param_names: ["id"],
  },
  "0x141a468c": {
    name: "nonces",
    signature: "nonces(uint256)",
    types: ["uint256"],
    param_names: ["tokenId"],
  },
  "0x14ab9038": {
    name: "setTTL",
    signature: "setTTL(bytes32,uint64)",
    types: ["bytes32", "uint64"],
    param_names: ["node", "ttl"],
  },
  "0x16a25cbd": {
    name: "ttl",
    signature: "ttl(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
  "0x18160ddd": {
    name: "totalSupply",
    signature: "totalSupply()",
    types: [],
    param_names: [],
  },
  "0x1896f70a": {
    name: "setResolver",
    signature: "setResolver(bytes32,address)",
    types: ["bytes32", "address"],
    param_names: ["node", "resolver"],
  },
  "0x205c2878": {
    name: "withdrawTo",
    signature: "withdrawTo(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["account", "value"],
  },
  "0x23b872dd": {
    name: "transferFrom",
    signature: "transferFrom(address,address,uint256)",
    types: ["address", "address", "uint256"],
    param_names: ["from", "to", "value"],
  },
  "0x2a55205a": {
    name: "royaltyInfo",
    signature: "royaltyInfo(uint256,uint256)",
    types: ["uint256", "uint256"],
    param_names: ["tokenId", "salePrice"],
  },
  "0x2eb2c2d6": {
    name: "safeBatchTransferFrom",
    signature:
      "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)",
    types: [
      "address",
      "address",
      "uint256[]",
      "uint256[]",
      "bytes",
    ],
    param_names: ["from", "to", "ids", "values", "data"],
  },
  "0x2f4f21e2": {
    name: "depositFor",
    signature: "depositFor(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["account", "value"],
  },
  "0x2f745c59": {
    name: "tokenOfOwnerByIndex",
    signature: "tokenOfOwnerByIndex(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["owner", "index"],
  },
  "0x313ce567": {
    name: "decimals",
    signature: "decimals()",
    types: [],
    param_names: [],
  },
  "0x355274ea": {
    name: "cap",
    signature: "cap()",
    types: [],
    param_names: [],
  },
  "0x3644e515": {
    name: "DOMAIN_SEPARATOR",
    signature: "DOMAIN_SEPARATOR()",
    types: [],
    param_names: [],
  },
  "0x38d52e0f": {
    name: "asset",
    signature: "asset()",
    types: [],
    param_names: [],
  },
  "0x3a46b1a8": {
    name: "getPastVotes",
    signature: "getPastVotes(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["account", "timepoint"],
  },
  "0x3b3b57de": {
    name: "addr",
    signature: "addr(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
  "0x3f4ba83a": {
    name: "unpause",
    signature: "unpause()",
    types: [],
    param_names: [],
  },
  "0x402d267d": {
    name: "maxDeposit",
    signature: "maxDeposit(address)",
    types: ["address"],
    param_names: ["receiver"],
  },
  "0x40c10f19": {
    name: "mint",
    signature: "mint(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["to", "amount"],
  },
  "0x42842e0e": {
    name: "safeTransferFrom",
    signature: "safeTransferFrom(address,address,uint256)",
    types: ["address", "address", "uint256"],
    param_names: ["from", "to", "tokenId"],
  },
  "0x42966c68": {
    name: "burn",
    signature: "burn(uint256)",
    types: ["uint256"],
    param_names: ["value"],
  },
  "0x445bb62d": {
    name: "open",
    signature: "open(tuple)",
    types: ["tuple"],
    param_names: ["order"],
  },
  "0x4bf5d7e9": {
    name: "CLOCK_MODE",
    signature: "CLOCK_MODE()",
    types: [],
    param_names: [],
  },
  "0x4cdad506": {
    name: "previewRedeem",
    signature: "previewRedeem(uint256)",
    types: ["uint256"],
    param_names: ["shares"],
  },
  "0x4d1f9583": {
    name: "announce",
    signature: "announce(uint256,address,bytes,bytes)",
    types: ["uint256", "address", "bytes", "bytes"],
    param_names: [
      "schemeId",
      "stealthAddress",
      "ephemeralPubKey",
      "metadata",
    ],
  },
  "0x4e1273f4": {
    name: "balanceOfBatch",
    signature: "balanceOfBatch(address[],uint256[])",
    types: ["address[]", "uint256[]"],
    param_names: ["accounts", "ids"],
  },
  "0x4f6ccce7": {
    name: "tokenByIndex",
    signature: "tokenByIndex(uint256)",
    types: ["uint256"],
    param_names: ["index"],
  },
  "0x587cde1e": {
    name: "delegates",
    signature: "delegates(address)",
    types: ["address"],
    param_names: ["account"],
  },
  "0x59d1d43c": {
    name: "text",
    signature: "text(bytes32,string)",
    types: ["bytes32", "string"],
    param_names: ["node", "key"],
  },
  "0x5b0fc9c3": {
    name: "setOwner",
    signature: "setOwner(bytes32,address)",
    types: ["bytes32", "address"],
    param_names: ["node", "owner"],
  },
  "0x5c19a95c": {
    name: "delegate",
    signature: "delegate(address)",
    types: ["address"],
    param_names: ["delegatee"],
  },
  "0x5c975abb": {
    name: "paused",
    signature: "paused()",
    types: [],
    param_names: [],
  },
  "0x5cffe9de": {
    name: "flashLoan",
    signature: "flashLoan(address,address,uint256,bytes)",
    types: ["address", "address", "uint256", "bytes"],
    param_names: ["receiver", "token", "amount", "data"],
  },
  "0x5ef2c7f0": {
    name: "setSubnodeRecord",
    signature:
      "setSubnodeRecord(bytes32,bytes32,address,address,uint64)",
    types: [
      "bytes32",
      "bytes32",
      "address",
      "address",
      "uint64",
    ],
    param_names: [
      "node",
      "label",
      "owner",
      "resolver",
      "ttl",
    ],
  },
  "0x613255ab": {
    name: "maxFlashLoan",
    signature: "maxFlashLoan(address)",
    types: ["address"],
    param_names: ["token"],
  },
  "0x6352211e": {
    name: "ownerOf",
    signature: "ownerOf(uint256)",
    types: ["uint256"],
    param_names: ["tokenId"],
  },
  "0x68d8b4f2": {
    name: "resolve",
    signature: "resolve(tuple)",
    types: ["tuple"],
    param_names: ["order"],
  },
  "0x691f3431": {
    name: "name",
    signature: "name(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
  "0x6e553f65": {
    name: "deposit",
    signature: "deposit(uint256,address)",
    types: ["uint256", "address"],
    param_names: ["assets", "receiver"],
  },
  "0x6f307dc3": {
    name: "underlying",
    signature: "underlying()",
    types: [],
    param_names: [],
  },
  "0x70a08231": {
    name: "balanceOf",
    signature: "balanceOf(address)",
    types: ["address"],
    param_names: ["account"],
  },
  "0x745a41bc": {
    name: "permit",
    signature: "permit(address,uint256,uint256,bytes)",
    types: ["address", "uint256", "uint256", "bytes"],
    param_names: ["spender", "tokenId", "deadline", "sig"],
  },
  "0x79cc6790": {
    name: "burnFrom",
    signature: "burnFrom(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["account", "value"],
  },
  "0x7ecebe00": {
    name: "nonces",
    signature: "nonces(address)",
    types: ["address"],
    param_names: ["owner"],
  },
  "0x7ffb7f9b": {
    name: "openFor",
    signature: "openFor(tuple,bytes,bytes)",
    types: ["tuple", "bytes", "bytes"],
    param_names: ["order", "signature", "originFillerData"],
  },
  "0x82e2c43f": {
    name: "fill",
    signature: "fill(bytes32,bytes,bytes)",
    types: ["bytes32", "bytes", "bytes"],
    param_names: ["orderId", "originData", "fillerData"],
  },
  "0x8456cb59": {
    name: "pause",
    signature: "pause()",
    types: [],
    param_names: [],
  },
  "0x8e539e8c": {
    name: "getPastTotalSupply",
    signature: "getPastTotalSupply(uint256)",
    types: ["uint256"],
    param_names: ["timepoint"],
  },
  "0x91ddadf4": {
    name: "clock",
    signature: "clock()",
    types: [],
    param_names: [],
  },
  "0x94bf804d": {
    name: "mint",
    signature: "mint(uint256,address)",
    types: ["uint256", "address"],
    param_names: ["shares", "receiver"],
  },
  "0x95d89b41": {
    name: "symbol",
    signature: "symbol()",
    types: [],
    param_names: [],
  },
  "0x9ab24eb0": {
    name: "getVotes",
    signature: "getVotes(address)",
    types: ["address"],
    param_names: ["account"],
  },
  "0xa22cb465": {
    name: "setApprovalForAll",
    signature: "setApprovalForAll(address,bool)",
    types: ["address", "bool"],
    param_names: ["operator", "approved"],
  },
  "0xa9059cbb": {
    name: "transfer",
    signature: "transfer(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["to", "value"],
  },
  "0xb3d7f6b9": {
    name: "previewMint",
    signature: "previewMint(uint256)",
    types: ["uint256"],
    param_names: ["shares"],
  },
  "0xb460af94": {
    name: "withdraw",
    signature: "withdraw(uint256,address,address)",
    types: ["uint256", "address", "address"],
    param_names: ["assets", "receiver", "owner"],
  },
  "0xb88d4fde": {
    name: "safeTransferFrom",
    signature:
      "safeTransferFrom(address,address,uint256,bytes)",
    types: ["address", "address", "uint256", "bytes"],
    param_names: ["from", "to", "tokenId", "data"],
  },
  "0xba087652": {
    name: "redeem",
    signature: "redeem(uint256,address,address)",
    types: ["uint256", "address", "address"],
    param_names: ["shares", "receiver", "owner"],
  },
  "0xc3cda520": {
    name: "delegateBySig",
    signature:
      "delegateBySig(address,uint256,uint256,uint8,bytes32,bytes32)",
    types: [
      "address",
      "uint256",
      "uint256",
      "uint8",
      "bytes32",
      "bytes32",
    ],
    param_names: [
      "delegatee",
      "nonce",
      "expiry",
      "v",
      "r",
      "s",
    ],
  },
  "0xc63d75b6": {
    name: "maxMint",
    signature: "maxMint(address)",
    types: ["address"],
    param_names: ["receiver"],
  },
  "0xc6e6f592": {
    name: "convertToShares",
    signature: "convertToShares(uint256)",
    types: ["uint256"],
    param_names: ["assets"],
  },
  "0xc87b56dd": {
    name: "tokenURI",
    signature: "tokenURI(uint256)",
    types: ["uint256"],
    param_names: ["tokenId"],
  },
  "0xce96cb77": {
    name: "maxWithdraw",
    signature: "maxWithdraw(address)",
    types: ["address"],
    param_names: ["owner"],
  },
  "0xcf408823": {
    name: "setRecord",
    signature: "setRecord(bytes32,address,address,uint64)",
    types: ["bytes32", "address", "address", "uint64"],
    param_names: ["node", "owner", "resolver", "ttl"],
  },
  "0xd505accf": {
    name: "permit",
    signature:
      "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)",
    types: [
      "address",
      "address",
      "uint256",
      "uint256",
      "uint8",
      "bytes32",
      "bytes32",
    ],
    param_names: [
      "owner",
      "spender",
      "value",
      "deadline",
      "v",
      "r",
      "s",
    ],
  },
  "0xd905777e": {
    name: "maxRedeem",
    signature: "maxRedeem(address)",
    types: ["address"],
    param_names: ["owner"],
  },
  "0xd9d98ce4": {
    name: "flashFee",
    signature: "flashFee(address,uint256)",
    types: ["address", "uint256"],
    param_names: ["token", "amount"],
  },
  "0xdd62ed3e": {
    name: "allowance",
    signature: "allowance(address,address)",
    types: ["address", "address"],
    param_names: ["owner", "spender"],
  },
  "0xe985e9c5": {
    name: "isApprovedForAll",
    signature: "isApprovedForAll(address,address)",
    types: ["address", "address"],
    param_names: ["account", "operator"],
  },
  "0xef8b30f7": {
    name: "previewDeposit",
    signature: "previewDeposit(uint256)",
    types: ["uint256"],
    param_names: ["assets"],
  },
  "0xf1cb7e06": {
    name: "addr",
    signature: "addr(bytes32,uint256)",
    types: ["bytes32", "uint256"],
    param_names: ["node", "coinType"],
  },
  "0xf242432a": {
    name: "safeTransferFrom",
    signature:
      "safeTransferFrom(address,address,uint256,uint256,bytes)",
    types: [
      "address",
      "address",
      "uint256",
      "uint256",
      "bytes",
    ],
    param_names: ["from", "to", "id", "value", "data"],
  },
  "0xf79fe538": {
    name: "recordExists",
    signature: "recordExists(bytes32)",
    types: ["bytes32"],
    param_names: ["node"],
  },
} as const

export type RegistrySelector = keyof typeof REGISTRY
export type RegistryEntry =
  (typeof REGISTRY)[RegistrySelector]
